export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{ padding: "1rem", backgroundColor: "#333", color: "#fff" }}
        >
          <p>Header</p>
        </header>

        {children}
        
        <footer
          style={{
            padding: "1rem",
            backgroundColor: "#333",
            color: "#fff",
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
